name: CMake

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:

  build:

    runs-on: ["sunny"]

    steps:
    - uses: actions/checkout@v3
    - name: Prajna CI
      run: cd  dockerfiles && docker build . --file ubuntu_dev.dockerfile
