name: CMake

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]


jobs:

  build:

    runs-on: [self-hosted, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Prajna CI
    - run: nvidia-smi
    # - run: cd  dockerfiles && docker build . --file ubuntu_dev_nvgpu.dockerfile -t ubuntu_nvgpu
    # - run: docker run
