name: Remote Docker Test Workflow

on: [push, pull_request, workflow_dispatch]

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH and run commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.USER_PASSWORD }}
        script: |
          docker exec ${{ secrets.DOCKER_CONTAINER_ID }} /bin/bash -c "
          export PATH=\"/usr/local/cmake-3.25.2-linux-x86_64/bin:$PATH\"
          cd /prajna && rm -rf /prajna/build_release/*
          git pull > /dev/null 2>&1 || true
          ./scripts/configure.sh release > ./scripts/configure.log
          ./scripts/build.sh release > ./scripts/build.log
          ./scripts/test.sh release
          "
